Update again
nguyenhongson1996/water-quality-research pull request #2
Opened 2024-10-02 22:51 UTC by tienhxh

Create another module for sklearn base model

2024-10-04 03:15 UTC, nguyenhongson1996 requested changes
The changes are generally good.

2024-10-04 03:15 UTC, nguyenhongson1996 commented on ersPCtest_codeteststest_scikit.py
> +
What is this file?

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +import numpy as np
```suggestion
import os
import sys
from abc import abstractmethod
from typing import Any, Dict, Optional, Tuple

import numpy as np
from sklearn.linear_model import SGDRegressor, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


# Get the directory path of the current Python file.
file_dir = os.path.dirname(__file__)

# Add the parent directory to the system path.
sys.path.append(os.path.join(file_dir, 'C:\\Users\\PC\\test_code'))
```

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +sys.path.append(os.path.join(file_dir, 'C:\\Users\\PC\\test_code'))
Why do we need this?

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +        :param input_dim: Input dimension (used for compatibility, not necessary for scikit-learn).
Where is this parameter?

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +    def __init__(self, model_type: str = 'sgd', lr: float = 0.001):
Because the parameters are different among models, let use ** kwargs to accept different parameters

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +    def __init__(self, model_type: str = 'sgd', lr: float = 0.001):
```suggestion
    def __init__(self, model_type: str = 'sgd', lr: float = 0.001, **kwargs: Optional[Dict[str, Any]]=None):
```

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +        self.model = self._build_model(model_type)
```suggestion
        self.model = self._build_model(model_type, **kwargs)
```

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +            raise ValueError(f"Unsupported model type: {model_type}")
```suggestion
    def _build_model(self, model_type: str, **kwargs: Optional[Dict[str, Any]] = None):
        """
        Construct the regression model.
        """
        raise NotImplementedError()
```

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +    def _build_model(self, model_type: str):
For each model, we will create a child class that inherits this class and in that child class, we implement this _build_model function.

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +            self.model.partial_fit(X_train, y_train)  # Incremental training
Add a comment explain why we are using partial_fit.

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +            self.model.partial_fit(X_train, y_train)  # Incremental training
```suggestion
            self.model.partial_fit(X_train, y_train)  # Incremental training.
```

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/regression/simple_scikit.py
> +    def forward(self, batch: np.ndarray):
What is the difference between this function and the predict function bellow?

2024-10-04 03:15 UTC, nguyenhongson1996 commented on tests/test_scikit.py
> +sys.path.append(os.path.join(file_dir, 'C:\\Users\\PC\\test_code'))
Do not use abspath. Again, why do we need this. Also let sort imports.

2024-10-04 03:15 UTC, nguyenhongson1996 commented on models/regression/simple_scikit.py
> +from models.base_scikitlearn_model import BaseModel
Sort imports

2024-10-04 03:15 UTC, nguyenhongson1996 commented on tests/test_scikit.py
> +    features, targets = [], []
Typing.

2024-10-04 03:15 UTC, nguyenhongson1996 commented on tests/test_scikit.py
> +    print(f'True Value: {y_test[i]}, Predicted Value: {y_pred[i]}')
```suggestion
    print(f'True Value: {y_test[i]}, Predicted Value: {y_pred[i]}')
    
```

2024-10-05 03:50 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +sys.path.append(os.path.join(file_dir, 'C:\\Users\\PC\\test_code'))
Why do we need this? You can simply use `export PYTHONPATH=.` at the root folder.

2024-10-05 03:53 UTC, nguyenhongson1996 requested changes
There are some comments need to be addressed.

2024-10-05 03:53 UTC, nguyenhongson1996 commented on models/regression/simple_scikit.py
> +    def forward(self, batch: np.ndarray):
Not addressed.

2024-10-05 03:53 UTC, nguyenhongson1996 commented on tests/test_scikit.py
> +sys.path.append(os.path.join(file_dir, 'C:\\Users\\PC\\test_code'))
Not addressed.

2024-10-05 04:03 UTC, tienhxh commented on models/base_scikitlearn_model.py
> +sys.path.append(os.path.join(file_dir, 'C:\\Users\\PC\\test_code'))
When i clone from Github and run code, it has a error: ModuleNotFoundError, so i have to get the abspath.

2024-10-05 05:17 UTC, nguyenhongson1996 approved these changes
LGTM

2024-10-05 05:17 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +from sklearn.metrics import mean_squared_error
```suggestion
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
```

2024-10-05 05:17 UTC, nguyenhongson1996 commented on models/base_scikitlearn_model.py
> +            # partial_fit allows the model to be updated with new batches of data without needing to retrain from scratch.
update this comment since we are using fit instead of partial_fit now

2024-10-05 05:17 UTC, nguyenhongson1996 commented on models/regression/simple_scikit.py
> +from models.base_scikitlearn_model import BaseModel
```suggestion
from sklearn.metrics import mean_squared_error

from models.base_scikitlearn_model import BaseModel
```

2024-10-05 05:17 UTC, nguyenhongson1996 commented on utils/data_utils.py
> +    date_full =['2011/01', '2011/02', '2011/03', '2011/04', '2011/05', '2011/06',
Where do we use this constant?

2024-10-05 05:17 UTC, nguyenhongson1996 commented on models/regression/simple_scikit.py
> +class BasicRegression(BaseModel):
Use another name to make it clear, e.g. SimpleSklearnRegression

2024-10-05 05:42 UTC, merged