update CNN 12/10
nguyenhongson1996/water-quality-research pull request #6
Opened 2024-10-12 14:29 UTC by sukcheon22

Build a CNN architecture with one CNN layer

2024-10-17 07:49 UTC, nguyenhongson1996 requested changes
Can you also add the evaluation result to the PR description?

2024-10-17 07:49 UTC, nguyenhongson1996 commented on models/regression/simple_regression.py
> +        self.cnn = nn.Conv1d(in_channels=input_dim, out_channels=1, kernel_size=1)
```suggestion
        self.cnn = nn.Conv1d(in_channels=input_dim, out_channels=1, kernel_size=1)
        
```

2024-10-17 07:49 UTC, nguyenhongson1996 commented on models/regression/simple_regression.py
> +            input equal to 1.
We should use reStructuredText as the format

2024-10-17 07:49 UTC, nguyenhongson1996 commented on models/regression/simple_regression.py
> +            Build CNN with PyTorch
```suggestion
            Build CNN using PyTorch.
```

2024-10-17 07:49 UTC, nguyenhongson1996 commented on models/regression/simple_regression.py
> +            view(data.size(0), -1): flatten to 2D.
We should move this description to the code part and use # to comment.

2024-10-17 07:49 UTC, nguyenhongson1996 commented on models/regression/simple_regression.py
> +        data = data.unsqueeze(1)
```suggestion
        # Add a dimension to data so as to be suitable for Conv1d layer (batch_size, input_dim) -> (batch_size, 1, input_dim).
        data = data.unsqueeze(1)   
```

2024-10-17 07:49 UTC, nguyenhongson1996 commented on models/regression/simple_regression.py
> +        data = data.unsqueeze(1)
Ditto for bellow. And why we use 1 as the dimension size

2024-10-20 08:08 UTC, sukcheon22 reviewed
Early stopping after 121 epochs, Train Loss: 8.1190, Val Loss: 9.4742

2024-10-27 05:12 UTC, nguyenhongson1996 approved these changes
LGTM. There are some small comments need to be addresed.

2024-11-18 00:18 UTC, merged